/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RDICT_H_RPCGEN
#define _RDICT_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define MAXWORD 50
#define DICTSIZ 100
#define CATSIZE 5100

struct upd {
	char *upd_old;
	char *upd_new;
};
typedef struct upd upd;
#ifdef __cplusplus
extern "C" bool_t xdr_upd(XDR *, upd*);
#elif __STDC__
extern  bool_t xdr_upd(XDR *, upd*);
#else /* Old Style C */
bool_t xdr_upd();
#endif /* Old Style C */


#define RDICTPROG ((rpc_uint)0x30090949)
#define RDICTVERS ((rpc_uint)1)

#ifdef __cplusplus
#define INITW ((rpc_uint)1)
extern "C" int * initw_1(void *, CLIENT *);
extern "C" int * initw_1_svc(void *, struct svc_req *);
#define INSERTW ((rpc_uint)2)
extern "C" int * insertw_1(char **, CLIENT *);
extern "C" int * insertw_1_svc(char **, struct svc_req *);
#define DELETEW ((rpc_uint)3)
extern "C" int * deletew_1(char **, CLIENT *);
extern "C" int * deletew_1_svc(char **, struct svc_req *);
#define LOOKUPW ((rpc_uint)4)
extern "C" int * lookupw_1(char **, CLIENT *);
extern "C" int * lookupw_1_svc(char **, struct svc_req *);
#define UPDATEW ((rpc_uint)5)
extern "C" int * updatew_1(upd *, CLIENT *);
extern "C" int * updatew_1_svc(upd *, struct svc_req *);
#define COUNTW ((rpc_uint)6)
extern "C" int * countw_1(void *, CLIENT *);
extern "C" int * countw_1_svc(void *, struct svc_req *);
#define SELECTW ((rpc_uint)7)
extern "C" char ** selectw_1(void *, CLIENT *);
extern "C" char ** selectw_1_svc(void *, struct svc_req *);

#elif __STDC__
#define INITW ((rpc_uint)1)
extern  int * initw_1(void *, CLIENT *);
extern  int * initw_1_svc(void *, struct svc_req *);
#define INSERTW ((rpc_uint)2)
extern  int * insertw_1(char **, CLIENT *);
extern  int * insertw_1_svc(char **, struct svc_req *);
#define DELETEW ((rpc_uint)3)
extern  int * deletew_1(char **, CLIENT *);
extern  int * deletew_1_svc(char **, struct svc_req *);
#define LOOKUPW ((rpc_uint)4)
extern  int * lookupw_1(char **, CLIENT *);
extern  int * lookupw_1_svc(char **, struct svc_req *);
#define UPDATEW ((rpc_uint)5)
extern  int * updatew_1(upd *, CLIENT *);
extern  int * updatew_1_svc(upd *, struct svc_req *);
#define COUNTW ((rpc_uint)6)
extern  int * countw_1(void *, CLIENT *);
extern  int * countw_1_svc(void *, struct svc_req *);
#define SELECTW ((rpc_uint)7)
extern  char ** selectw_1(void *, CLIENT *);
extern  char ** selectw_1_svc(void *, struct svc_req *);

#else /* Old Style C */
#define INITW ((rpc_uint)1)
extern  int * initw_1();
extern  int * initw_1_svc();
#define INSERTW ((rpc_uint)2)
extern  int * insertw_1();
extern  int * insertw_1_svc();
#define DELETEW ((rpc_uint)3)
extern  int * deletew_1();
extern  int * deletew_1_svc();
#define LOOKUPW ((rpc_uint)4)
extern  int * lookupw_1();
extern  int * lookupw_1_svc();
#define UPDATEW ((rpc_uint)5)
extern  int * updatew_1();
extern  int * updatew_1_svc();
#define COUNTW ((rpc_uint)6)
extern  int * countw_1();
extern  int * countw_1_svc();
#define SELECTW ((rpc_uint)7)
extern  char ** selectw_1();
extern  char ** selectw_1_svc();
#endif /* Old Style C */

#endif /* !_RDICT_H_RPCGEN */
